# Generated by Django 5.0.4 on 2024-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
