# Generated by Django 5.0.4 on 2024-05-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_models', '0002_jobdescription_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='company_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/', verbose_name='company picture'),
        ),
        migrations.AlterField(
            model_name='careersbucketbaseuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile picture'),
        ),
    ]
