# Generated by Django 5.0.4 on 2024-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_models', '0003_jobdescription_company_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='experience_level',
            field=models.CharField(default='Entry Lever', max_length=150, verbose_name='Experience required '),
        ),
    ]
